### ISSUE TITLE
创建一个Activity就要重写ViewBinding自动生成的类么？

### ISSUE THREAD

**Issue by thisleo** [choimroc/ViewBindingDemo#1]
demo中的ActivityMainBinding类是自己写的，不用ViewBinding 自动生成的么？

**Comment by choimroc** [comment]
@thisleo 文章中的第五节是我自己写的viewbinding，只是提供一种思路。第三节的才是Android studio自动生成的，不需要自己写

**Comment by thisleo** [comment]
> @thisleo 文章中的第五节是我自己写的viewbinding，只是提供一种思路。第三节的才是Android studio自动生成的，不需要自己写

ViewBinding这个类需要重写，自动生成的类怎么引用自己写的ViewBinding呢？

**Comment by thisleo** [comment]
![image](https://user-images.githubusercontent.com/24713476/104575061-b7460c80-5691-11eb-9025-8206656b640b.png)
这样重写ViewBinding这个接口么？

**Comment by choimroc** [comment]
@thisleo 不需要自己重写的，viewbinding是自动生成，在app的`build/generated/data_binding_base_class_source_out/debug/out`目录中。你如果想要使用，参考文章第三节`3 基于ViewBinding的BaseActivity`就行，重写的那个是我自己觉得那样做会更方便封装，但是实际上，官方为了安全，并没有使用我所说的那种方案。

**Comment by thisleo** [comment]
> @thisleo 不需要自己重写的，viewbinding是自动生成，在app的`build/generated/data_binding_base_class_source_out/debug/out`目录中。你如果想要使用，参考文章第三节`3 基于ViewBinding的BaseActivity`就行，重写的那个是我自己觉得那样做会更方便封装，但是实际上，官方为了安全，并没有使用我所说的那种方案。

好的，明白了，谢谢大佬
